remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navbar-links:
  About Me: "aboutme"
  Resources:
    - Learn Balkeon: "https://www.metroman.me/balkeon"
  Author's home: "https://www.metroman.me"
