remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navbar-links:
  About Me: "aboutme"
  Resources:
    - Learn Balkeon: "https://www.metroman.me/balkeon"
  Author's home: "https://www.metroman.me"

avatar: "https://cdn.discordapp.com/attachments/1304811037614149662/1309588649997897728/MetroManTransp.png.jpg?ex=674220f9&is=6740cf79&hm=879859d62402905bba6287f50f44c59daf9e0f0b9aeab8bf2d10e4b7e0a473ee&"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true
